-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. ENUMS (Tipos de datos personalizados)
create type property_status as enum ('disponible', 'reservado', 'vendido');
create type currency_code as enum ('USD', 'ARS', 'UYU');
create type operation_type as enum ('venta', 'alquiler', 'alquiler_temporal');

-- 2. PUBLIC PROFILES (Perfiles de empleados vinculados a auth.users)
create table public.public_profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'agent', -- admin, agent
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.public_profiles enable row level security;

-- Políticas de seguridad (RLS) para profiles
create policy "Public profiles are viewable by everyone."
  on public.public_profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.public_profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.public_profiles for update
  using ( auth.uid() = id );

-- Trigger para crear perfil público automáticamente al registrarse
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.public_profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. PROPERTIES (Tabla principal de propiedades)
create table public.properties (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Información Básica
  title text not null,
  slug text unique not null, -- Para URLs amigables (SEO)
  description text,
  
  -- Estado y Operación
  status property_status default 'disponible'::property_status,
  operation operation_type default 'venta'::operation_type,
  
  -- Precio
  price numeric,
  currency currency_code default 'USD'::currency_code,
  
  -- Características
  bedrooms integer default 0,
  bathrooms integer default 0,
  covered_area numeric default 0, -- Metros cuadrados cubiertos
  total_area numeric default 0,   -- Metros cuadrados totales
  garage boolean default false,
  
  -- Ubicación (Lat/Lng para Leaflet)
  location_lat double precision,
  location_lng double precision,
  address text,
  city text,
  
  -- Multimedia
  images text[] default '{}', -- Array de URLs de imágenes optimizadas
  video_url text,
  
  -- Relaciones
  agent_id uuid references public.public_profiles(id),
  featured boolean default false -- Propiedad destacada en Home
);

-- Políticas RLS para properties
alter table public.properties enable row level security;

create policy "Properties are viewable by everyone."
  on public.properties for select
  using ( true );

create policy "Agents can insert properties."
  on public.properties for insert
  with check ( auth.role() = 'authenticated' ); -- Ajustar según lógica de roles si es necesario

create policy "Agents can update properties."
  on public.properties for update
  using ( auth.role() = 'authenticated' );

create policy "Agents can delete properties."
  on public.properties for delete
  using ( auth.role() = 'authenticated' );


-- 4. TAGS (Categorías extra como "Piscina", "Vista al mar", etc.)
create table public.tags (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tags enable row level security;

create policy "Tags are viewable by everyone."
  on public.tags for select using ( true );

create policy "Agents can insert tags."
  on public.tags for insert with check ( auth.role() = 'authenticated' );

-- 5. PROPERTY_TAGS (Relación N a N)
create table public.property_tags (
  property_id uuid references public.properties(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (property_id, tag_id)
);

alter table public.property_tags enable row level security;

create policy "Property tags are viewable by everyone."
  on public.property_tags for select using ( true );

create policy "Agents can manage property tags."
  on public.property_tags for all using ( auth.role() = 'authenticated' );

-- 6. STORAGE BUCKET CONFIGURATION (Script opcional si no se hace desde UI)
-- Nota: Usualmente se configura desde la UI de Supabase, pero aquí insertamos la política si el bucket existiera.
-- Insertar bucket 'propiedades-img' (requiere permisos de admin o hacerlo desde dashboard)
insert into storage.buckets (id, name, public) values ('propiedades-img', 'propiedades-img', true)
on conflict (id) do nothing;

-- Política de Storage: Cualquiera puede ver, solo autenticados pueden subir
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'propiedades-img' );

create policy "Authenticated Agent Upload"
  on storage.objects for insert
  with check ( bucket_id = 'propiedades-img' and auth.role() = 'authenticated' );

create policy "Authenticated Agent Update"
  on storage.objects for update
  with check ( bucket_id = 'propiedades-img' and auth.role() = 'authenticated' );

create policy "Authenticated Agent Delete"
  on storage.objects for delete
  using ( bucket_id = 'propiedades-img' and auth.role() = 'authenticated' );
